### ISSUE TITLE
Errors on browserify -r 

### ISSUE THREAD

**Issue by laduke** [browserify/common-shakeify#29]
Made a repro here
https://github.com/laduke/common-shake-repro

Hopefully i'm not just holding it wrong.
Looks like same message as from #10 ?

```
 browserify -r net-browserify-stub:net index.js -p common-shakeify
```

```
/common-shake-repro/node_modules/common-shakeify/index.js:239
  return row[kDuplicates] || [

TypeError: Cannot read property 'Symbol(duplicates)' of undefined
    at getDuplicates (/Users/travis/src/common-shake-repro/node_modules/common-shakeify/index.js:239:13)
    at analyzer.modules.forEach (/Users/travis/src/common-shake-repro/node_modules/common-shakeify/index.js:122:21)
    at Map.forEach (<anonymous>)
    at DestroyableTransform.onend [as _flush] (/Users/travis/src/common-shake-repro/node_modules/common-shakeify/index.js:119:22)
    at DestroyableTransform.prefinish (/Users/travis/src/common-shake-repro/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:197:13)
    at prefinish (/Users/travis/src/common-shake-repro/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/Users/travis/src/common-shake-repro/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/Users/travis/src/common-shake-repro/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/Users/travis/src/common-shake-repro/node_modules/readable-stream/lib/_stream_writable.js:594:41)
```

**Comment by goto-bus-stop** [comment]
And #21!
I will keep both open because I'm not sure if they're the same issue, although both are related to -r.

Thanks for this repro, nice and small! will be easy to just copy-paste it into the test suite here :)

**Comment by laduke** [comment]
It looks like when replacing something from node_modules (instead of a path) it's sometimes using just `foo` for the key, and sometimes it's using `node_modules/foo/index.js`

this seems to help!
https://github.com/laduke/common-shakeify/tree/dash-r
