### ISSUE TITLE
common-shakeify@0.6.1 crashes with browserify --full-paths option

### ISSUE THREAD

**Issue by feross** [browserify/common-shakeify#32]
Issue did not exist in common-shakeify@0.6.0.

In common-shakeify@0.6.1, I started getting this error:

```
/Users/feross/code/bitmidi.com/node_modules/common-shakeify/index.js:92
    Object.keys(row.indexDeps).forEach((name) => {
           ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at DestroyableTransform.onfile [as _transform] (/Users/feross/code/bitmidi.com/node_modules/common-shakeify/index.js:92:12)
    at DestroyableTransform.Transform._read (/Users/feross/code/bitmidi.com/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/feross/code/bitmidi.com/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at Labeled.Pipeline._write (/Users/feross/code/bitmidi.com/node_modules/stream-splicer/index.js:70:22)
    at doWrite (/Users/feross/code/bitmidi.com/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/feross/code/bitmidi.com/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Labeled.Writable.write (/Users/feross/code/bitmidi.com/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Labeled.ondata (/Users/feross/code/bitmidi.com/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at Labeled.emit (events.js:198:13)
/Users/feross/code/bitmidi.com/node_modules/disc/bin/discify:59
    if (err) throw err
             ^
```

Looking at the changes made for 0.6.1 this definitely seems like it was introduced there. Haven't had a chance to look further into the cause.

The full command I'm using is `browserify --no-detect-globals --extension mjs --plugin tinyify --full-paths .` with latest browserify.

**Comment by goto-bus-stop** [comment]
Crap, now I remember why I didn't use `row.indexDeps` in the first place :woman_facepalming: 
thanks for the report. I think with fullPaths we _can_ actually use `deps`, so could toggle which property it uses depending on whether that is enabled.

**Comment by goto-bus-stop** [comment]
:package: 0.6.2 disables the bugfix from 0.6.1 if you use --full-paths

**Comment by feross** [comment]
Thanks for the quick fix!
